recipe_sha: a097c604b06c83d212f1ff4e664539f534d3191b6db3a990ca01b989fc39a76b  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
      libpng:           1.6.44-hadc24fc_0              conda-forge
      libsqlite:        3.47.2-hee588c1_0              conda-forge
      libssh2:          1.11.1-hf672d98_0              conda-forge
      libstdcxx:        14.2.0-hc0a3c3a_1              conda-forge
      libstdcxx-ng:     14.2.0-h4852527_1              conda-forge
      libtiff:          4.7.0-hc4654cb_2               conda-forge
      libuuid:          2.38.1-h0b41bf4_0              conda-forge
      libwebp-base:     1.4.0-hd590300_0               conda-forge
      libxcb:           1.17.0-h8a09558_0              conda-forge
      libxcrypt:        4.4.36-hd590300_1              conda-forge
      libzlib:          1.3.1-hb9d3cd8_2               conda-forge
      mappy:            2.28-py310h397c9d8_3           bioconda
      matplotlib-base:  3.9.4-py310h68603db_0          conda-forge
      megalodon:        2.5.0-py310h1fe012e_3          local
      munkres:          1.1.4-pyh9f0ad1d_0             conda-forge
      ncurses:          6.5-he02047a_1                 conda-forge
      numpy:            2.2.0-py310h5851e9f_0          conda-forge
      ont-fast5-api:    4.1.3-pyhdfd78af_0             bioconda
      openjpeg:         2.5.3-h5fbd93e_0               conda-forge
      openssl:          3.4.0-hb9d3cd8_0               conda-forge
      packaging:        24.2-pyhd8ed1ab_2              conda-forge
      pandas:           2.2.3-py310h5eaa309_1          conda-forge
      patsy:            1.0.1-pyhd8ed1ab_1             conda-forge
      pillow:           11.0.0-py310hfeaa1f3_0         conda-forge
      pip:              24.3.1-pyh8b19718_0            conda-forge
      progressbar33:    2.4-py_0                       conda-forge
      pthread-stubs:    0.4-hb9d3cd8_1002              conda-forge
      pyparsing:        3.2.0-pyhd8ed1ab_2             conda-forge
      pysam:            0.22.1-py310h64e62c9_3         file:///opt/host-conda-bld
      python:           3.10.16-he725a3c_1_cpython     conda-forge
      python-dateutil:  2.9.0.post0-pyhff2d567_1       conda-forge
      python-tzdata:    2024.2-pyhd8ed1ab_1            conda-forge
      python_abi:       3.10-5_cp310                   conda-forge
      pytz:             2024.1-pyhd8ed1ab_0            conda-forge
      qhull:            2020.2-h434a139_5              conda-forge
      readline:         8.2-h8228510_1                 conda-forge
      scikit-learn:     1.6.0-py310h27f47ee_0          conda-forge
      scipy:            1.14.1-py310hfcf56fc_2         conda-forge
      seaborn:          0.13.2-hd8ed1ab_3              conda-forge
      seaborn-base:     0.13.2-pyhd8ed1ab_3            conda-forge
      setuptools:       75.6.0-pyhff2d567_1            conda-forge
      six:              1.17.0-pyhd8ed1ab_0            conda-forge
      statsmodels:      0.14.4-py310hf462985_0         conda-forge
      tar:              1.34-hb2e2bae_1                conda-forge
      threadpoolctl:    3.5.0-pyhc1e730c_0             conda-forge
      tk:               8.6.13-noxft_h4845f30_101      conda-forge
      tqdm:             4.67.1-pyhd8ed1ab_0            conda-forge
      tzdata:           2024b-hc8b5060_0               conda-forge
      unicodedata2:     15.1.0-py310ha75aee5_1         conda-forge
      wheel:            0.45.1-pyhd8ed1ab_1            conda-forge
      xorg-libxau:      1.0.12-hb9d3cd8_0              conda-forge
      xorg-libxdmcp:    1.1.5-hb9d3cd8_0               conda-forge
      zstd:             1.5.6-ha6fb4c9_0               conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  export PREFIX=/opt/conda/conda-bld/megalodon_1734308078821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
  export SRC_DIR=/opt/conda/conda-bld/megalodon_1734308078821/test_tmp
  import: 'megalodon'
  import: 'megalodon_extras'
  import: 'megalodon'
  import: 'megalodon_extras'
   megalodon --help
  Traceback (most recent call last):
    File "/opt/conda/conda-bld/megalodon_1734308078821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/megalodon", line 7, in <module>
      from megalodon.__main__ import _main
    File "/opt/conda/conda-bld/megalodon_1734308078821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/megalodon/__main__.py", line 4, in <module>
      from megalodon import megalodon_helper as mh, __version__
    File "/opt/conda/conda-bld/megalodon_1734308078821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/megalodon/megalodon_helper.py", line 63, in <module>
      SEQ_TO_INT_ARR = np.full(26, -1, dtype=np.uintp)
    File "/opt/conda/conda-bld/megalodon_1734308078821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/numpy/_core/numeric.py", line 353, in full
      multiarray.copyto(a, fill_value, casting='unsafe')
  OverflowError: Python integer -1 out of bounds for uint64
  WARNING: Tests failed for megalodon-2.5.0-py310h1fe012e_3.tar.bz2 - moving package to /opt/conda/conda-bld/broken
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3523, in test
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/megalodon_1734308078821/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3727, in build_tree
      test(pkg, config=metadata.config.copy(), stats=stats)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3537, in test
      tests_failed(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3584, in tests_failed
      raise CondaBuildUserError("TESTS FAILED: "  os.path.basename(pkg))
  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: megalodon-2.5.0-py310h1fe012e_3.tar.bz2
# Last 100 lines of the build log.
category: |-
  test failure
