recipe_sha: 7db2540f4a455f7a875d121918437eca1a39148ccb00c6b4351d7bfecf0aba9e  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |
  2024-07-22T08:07:11 Subdir: linux-64 Gathering repodata
  2024-07-22T08:07:11 linux-64 Writing pre-patch repodata
  2024-07-22T08:07:11 linux-64 Applying patch instructions
  2024-07-22T08:07:11 linux-64 Writing patched repodata
  2024-07-22T08:07:11 linux-64 Building current_repodata subset
  2024-07-22T08:07:11 Subdir: linux-aarch64 Gathering repodata
  2024-07-22T08:07:11 linux-aarch64 Writing pre-patch repodata
  2024-07-22T08:07:11 linux-aarch64 Applying patch instructions
  2024-07-22T08:07:11 linux-aarch64 Writing patched repodata
  2024-07-22T08:07:11 linux-aarch64 Building current_repodata subset
  2024-07-22T08:07:11 Subdir: noarch Gathering repodata
  2024-07-22T08:07:11 noarch Writing pre-patch repodata
  2024-07-22T08:07:11 noarch Applying patch instructions
  2024-07-22T08:07:11 noarch Writing patched repodata
  2024-07-22T08:07:11 noarch Building current_repodata subset
  2024-07-22T08:07:11 linux-aarch64 Writing current_repodata subset
  2024-07-22T08:07:11 noarch Writing current_repodata subset
  2024-07-22T08:07:11 linux-64 Writing current_repodata subset
  2024-07-22T08:07:11 linux-aarch64 Writing index HTML
  2024-07-22T08:07:11 noarch Writing index HTML
  2024-07-22T08:07:11 linux-64 Writing index HTML
  2024-07-22T08:07:11 Subdir: linux-64 Gathering repodata
  2024-07-22T08:07:11 linux-64 Writing pre-patch repodata
  2024-07-22T08:07:11 linux-64 Applying patch instructions
  2024-07-22T08:07:11 linux-64 Writing patched repodata
  2024-07-22T08:07:11 linux-64 Building current_repodata subset
  2024-07-22T08:07:11 linux-64 Writing current_repodata subset
  2024-07-22T08:07:11 linux-64 Writing index HTML
  2024-07-22T08:07:11 Subdir: linux-aarch64 Gathering repodata
  2024-07-22T08:07:11 linux-aarch64 Writing pre-patch repodata
  2024-07-22T08:07:11 linux-aarch64 Applying patch instructions
  2024-07-22T08:07:11 linux-aarch64 Writing patched repodata
  2024-07-22T08:07:11 linux-aarch64 Building current_repodata subset
  2024-07-22T08:07:11 Subdir: noarch Gathering repodata
  2024-07-22T08:07:11 linux-aarch64 Writing current_repodata subset
  2024-07-22T08:07:11 noarch Writing pre-patch repodata
  2024-07-22T08:07:11 linux-aarch64 Writing index HTML
  2024-07-22T08:07:11 noarch Applying patch instructions
  2024-07-22T08:07:11 noarch Writing patched repodata
  2024-07-22T08:07:11 noarch Building current_repodata subset
  2024-07-22T08:07:11 noarch Writing current_repodata subset
  2024-07-22T08:07:11 noarch Writing index HTML
  /opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py:501: UserWarning: RECIPE_PATH received is a file (/opt/recipe/meta.yaml).
  It should be a path to a folder.
  Forcing conda-build to use the recipe file.
    warnings.warn(
  WARNING: Multiple meta files found. The meta.yaml file in the base directory (/opt/recipe) will be used.
  WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
  Adding in variants from internal_defaults
  Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml
  Adding in variants from /opt/host-conda-bld/conda_build_config_1_-e_bioconda_utils-conda_build_config.yaml
  Adding in variants from /opt/recipe/conda_build_config.yaml
  Attempting to finalize metadata for blast
  Reloading output folder: ...working... done
  Getting pinned dependencies: ...working... done
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/conda-forge/linux-64/gcc_linux-64-10.4.0-h9215b83_13.conda'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fce42cd9db0>: Failed to resolve 'conda.anaconda.org' ([Errno -2] Name or service not known)")': /conda-forge/linux-64/gcc_linux-64-10.4.0-h9215b83_13.conda
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/conda-forge/linux-64/gcc_linux-64-10.4.0-h9215b83_13.conda'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fce42cd9f60>: Failed to resolve 'conda.anaconda.org' ([Errno -2] Name or service not known)")': /conda-forge/linux-64/gcc_linux-64-10.4.0-h9215b83_13.conda
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/conda-forge/linux-64/gcc_linux-64-10.4.0-h9215b83_13.conda'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /conda-forge/linux-64/gcc_linux-64-10.4.0-h9215b83_13.conda
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2308, in build
      output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 916, in expand_outputs
      for output_dict, m in deepcopy(_m).get_output_metadata_set(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 2737, in get_output_metadata_set
      conda_packages = finalize_outputs_pass(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 1095, in finalize_outputs_pass
      fm = finalize_metadata(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 650, in finalize_metadata
      build_unsat, host_unsat = add_upstream_pins(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 465, in add_upstream_pins
      build_deps, build_unsat, extra_run_specs_from_build = _read_upstream_pin_files(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 453, in _read_upstream_pin_files
      extra_run_specs = get_upstream_pins(m, precs, env)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 425, in get_upstream_pins
      loc, dist = execute_download_actions(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 392, in execute_download_actions
      pfe.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 891, in execute
      raise CondaMultiError(not_cancelled)
  conda.CondaMultiError: Encountered an SSL error. Most likely a certificate verification issue.

  Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/gcc_linux-64-10.4.0-h9215b83_13.conda (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

  Encountered an SSL error. Most likely a certificate verification issue.

  Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/gcc_linux-64-10.4.0-h9215b83_13.conda (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))
# Last 100 lines of the build log.
