recipe_sha: bce6d31ce8752ec4f9c121cd3ee1e42fbd4b8e41cfd4c660cba2015ae4781b1c  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
    126 |                                 first = first | curr;
        |                                                 ^~~~
  src/kmer.cc:129:25: error: 'first' was not declared in this scope
    129 |                         first = first >> 2;
        |                         ^~~~~
  src/kmer.cc:130:25: error: 'first_rev' was not declared in this scope
    130 |                         first_rev = Kmer::reverse_complement(first, kmer_size);
        |                         ^~~~~~~~~
  src/kmer.cc:133:33: error: 'item' was not declared in this scope; did you mean 'tm'?
    133 |                                 item = first;
        |                                 ^~~~
        |                                 tm
  src/kmer.cc:135:33: error: 'item' was not declared in this scope; did you mean 'tm'?
    135 |                                 item = first_rev;
        |                                 ^~~~
        |                                 tm
  src/kmer.cc:137:33: error: request for member 'insert' in 'kmerset', which is of non-class type 'int'
    137 |                         kmerset.insert(item);
        |                                 ^~~~~~
  src/kmer.cc:137:40: error: 'item' was not declared in this scope; did you mean 'tm'?
    137 |                         kmerset.insert(item);
        |                                        ^~~~
        |                                        tm
  src/kmer.cc:139:33: error: expected ';' before 'next'
    139 |                         uint64_t next = (first << 2) & BITMASK(2*kmer_size);
        |                                 ^~~~~
        |                                 ;
  src/kmer.cc:140:33: error: expected ';' before 'next_rev'
    140 |                         uint64_t next_rev = first_rev >> 2;
        |                                 ^~~~~~~~~
        |                                 ;
  src/kmer.cc:142:29: error: 'uint32_t' was not declared in this scope
    142 |                         for(uint32_t i=kmer_size; i<read.length(); i) { //next kmers
        |                             ^~~~~~~~
  src/kmer.cc:142:29: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  src/kmer.cc:142:51: error: 'i' was not declared in this scope
    142 |                         for(uint32_t i=kmer_size; i<read.length(); i) { //next kmers
        |                                                   ^
  src/kmer.cc:143:33: error: 'uint8_t' was not declared in this scope
    143 |                                 uint8_t curr = Kmer::map_base(read[i]);
        |                                 ^~~~~~~
  src/kmer.cc:143:33: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  src/kmer.cc:144:37: error: 'curr' was not declared in this scope
    144 |                                 if (curr > DNA_MAP::G) { // 'N' is encountered
        |                                     ^~~~
  src/kmer.cc:151:33: error: 'next' was not declared in this scope; did you mean 'std::next'?
    151 |                                 next |= curr;
        |                                 ^~~~
        |                                 std::next
  In file included from /opt/conda/conda-bld/squeakr_1733851565652/_build_env/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c/string:47,
                   from /opt/conda/conda-bld/squeakr_1733851565652/_build_env/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c/bits/locale_classes.h:40,
                   from /opt/conda/conda-bld/squeakr_1733851565652/_build_env/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c/bits/ios_base.h:41,
                   from /opt/conda/conda-bld/squeakr_1733851565652/_build_env/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c/ios:44,
                   from /opt/conda/conda-bld/squeakr_1733851565652/_build_env/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c/istream:40,
                   from /opt/conda/conda-bld/squeakr_1733851565652/_build_env/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c/fstream:40,
                   from src/kmer.cc:11:
  /opt/conda/conda-bld/squeakr_1733851565652/_build_env/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c/bits/stl_iterator_base_funcs.h:232:5: note: 'std::next' declared here
    232 |     next(_InputIterator __x, typename
        |     ^~~~
  src/kmer.cc:151:41: error: 'curr' was not declared in this scope
    151 |                                 next |= curr;
        |                                         ^~~~
  src/kmer.cc:152:41: error: expected ';' before 'tmp'
    152 |                                 uint64_t tmp = Kmer::reverse_complement_base(curr);
        |                                         ^~~~
        |                                         ;
  src/kmer.cc:153:33: error: 'tmp' was not declared in this scope; did you mean 'tm'?
    153 |                                 tmp <<= (kmer_size*2-2);
        |                                 ^~~
        |                                 tm
  src/kmer.cc:154:33: error: 'next_rev' was not declared in this scope
    154 |                                 next_rev = next_rev | tmp;
        |                                 ^~~~~~~~
  src/kmer.cc:160:41: error: request for member 'insert' in 'kmerset', which is of non-class type 'int'
    160 |                                 kmerset.insert(item);
        |                                         ^~~~~~
  make: *** [Makefile:80: obj/kmer.o] Error 1
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2558, in build
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/squeakr_1733851565652/work/conda_build.sh']' returned non-zero exit status 2.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
      raise BuildScriptException(str(exc), caused_by=exc) from exc
  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/squeakr_1733851565652/work/conda_build.sh']' returned non-zero exit status 2.
# Last 100 lines of the build log.
