recipe_sha: f638577f8e9ebf06faf3d77f0eb373cd259a044c0ee0efa5a5d5f7a89aa31a9b  # The commit at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  INFO:conda_build.source:Source cache directory is: /opt/mambaforge/envs/bioconda/conda-bld/src_cache
  Downloading source to cache: last-874_499c75e5f7.zip
  Downloading http://last.cbrc.jp/last-874.zip
  INFO:conda_build.source:Downloading source to cache: last-874_499c75e5f7.zip
  INFO:conda_build.source:Downloading http://last.cbrc.jp/last-874.zip
  WARNING:urllib3.connection:Certificate did not match expected hostname: last.cbrc.jp. Certificate: {'subject': ((('commonName', 'cbrc3.cbrc.jp'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)), 'version': 3, 'serialNumber': '046FF5BB109D36E9CD09D5B800EC565DA3D8', 'notBefore': 'Apr 14 19:04:49 2023 GMT', 'notAfter': 'Jul 13 19:04:48 2023 GMT', 'subjectAltName': (('DNS', 'cbrc3.cbrc.jp'),), 'OCSP': ('http://r3.o.lencr.org',), 'caIssuers': ('http://r3.i.lencr.org/',)}
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/last-874.zip'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError("hostname 'last.cbrc.jp' doesn't match 'cbrc3.cbrc.jp'"))': /last-874.zip
  WARNING:urllib3.connection:Certificate did not match expected hostname: last.cbrc.jp. Certificate: {'subject': ((('commonName', 'cbrc3.cbrc.jp'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)), 'version': 3, 'serialNumber': '046FF5BB109D36E9CD09D5B800EC565DA3D8', 'notBefore': 'Apr 14 19:04:49 2023 GMT', 'notAfter': 'Jul 13 19:04:48 2023 GMT', 'subjectAltName': (('DNS', 'cbrc3.cbrc.jp'),), 'OCSP': ('http://r3.o.lencr.org',), 'caIssuers': ('http://r3.i.lencr.org/',)}
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/last-874.zip'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError("hostname 'last.cbrc.jp' doesn't match 'cbrc3.cbrc.jp'"))': /last-874.zip
  WARNING:urllib3.connection:Certificate did not match expected hostname: last.cbrc.jp. Certificate: {'subject': ((('commonName', 'cbrc3.cbrc.jp'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)), 'version': 3, 'serialNumber': '046FF5BB109D36E9CD09D5B800EC565DA3D8', 'notBefore': 'Apr 14 19:04:49 2023 GMT', 'notAfter': 'Jul 13 19:04:48 2023 GMT', 'subjectAltName': (('DNS', 'cbrc3.cbrc.jp'),), 'OCSP': ('http://r3.o.lencr.org',), 'caIssuers': ('http://r3.i.lencr.org/',)}
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/last-874.zip'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError("hostname 'last.cbrc.jp' doesn't match 'cbrc3.cbrc.jp'"))': /last-874.zip
  WARNING:urllib3.connection:Certificate did not match expected hostname: last.cbrc.jp. Certificate: {'subject': ((('commonName', 'cbrc3.cbrc.jp'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)), 'version': 3, 'serialNumber': '046FF5BB109D36E9CD09D5B800EC565DA3D8', 'notBefore': 'Apr 14 19:04:49 2023 GMT', 'notAfter': 'Jul 13 19:04:48 2023 GMT', 'subjectAltName': (('DNS', 'cbrc3.cbrc.jp'),), 'OCSP': ('http://r3.o.lencr.org',), 'caIssuers': ('http://r3.i.lencr.org/',)}
  Traceback (most recent call last):
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
      httplib_response = self._make_request(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
      self._validate_conn(conn)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
      conn.connect()
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/urllib3/connection.py", line 397, in connect
      _match_hostname(cert, self.assert_hostname or server_hostname)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/urllib3/connection.py", line 407, in _match_hostname
      match_hostname(cert, asserted_hostname)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/ssl.py", line 420, in match_hostname
      raise CertificateError("hostname %r "
  ssl.SSLCertVerificationError: ("hostname 'last.cbrc.jp' doesn't match 'cbrc3.cbrc.jp'",)

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
      resp = conn.urlopen(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
      return self.urlopen(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
      return self.urlopen(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
      return self.urlopen(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
      retries = retries.increment(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))
  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='last.cbrc.jp', port=443): Max retries exceeded with url: /last-874.zip (Caused by SSLError(SSLCertVerificationError("hostname 'last.cbrc.jp' doesn't match 'cbrc3.cbrc.jp'")))

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda/gateways/connection/download.py", line 48, in download
      resp = session.get(url, stream=True, proxies=session.proxies, timeout=timeout)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/requests/sessions.py", line 546, in get
      return self.request('GET', url, **kwargs)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
      resp = self.send(prep, **send_kwargs)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/requests/sessions.py", line 668, in send
      history = [resp for resp in gen] if allow_redirects else []
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/requests/sessions.py", line 668, in <listcomp>
      history = [resp for resp in gen] if allow_redirects else []
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/requests/sessions.py", line 239, in resolve_redirects
      resp = self.send(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
      r = adapter.send(request, **kwargs)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
      raise SSLError(e, request=request)
  requests.exceptions.SSLError: HTTPSConnectionPool(host='last.cbrc.jp', port=443): Max retries exceeded with url: /last-874.zip (Caused by SSLError(SSLCertVerificationError("hostname 'last.cbrc.jp' doesn't match 'cbrc3.cbrc.jp'")))

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/mambaforge/envs/bioconda/bin/conda-mambabuild", line 10, in <module>
      sys.exit(main())
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
      call_conda_build(action, config)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
      result = api.build(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
      return build_tree(
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
      packages_from_this = build(metadata, stats,
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 2125, in build
      try_download(m, no_download_source=False, raise_error=True)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 650, in try_download
      source.provide(metadata)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/source.py", line 871, in provide
      unpack(source_dict, src_dir, metadata.config.src_cache, recipe_path=metadata.path,
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/source.py", line 146, in unpack
      src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/source.py", line 89, in download_to_cache
      download(url, path)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda/exports.py", line 374, in download
      return _download(url, dst_path, md5=md5sum, sha256=sha256, size=size)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda/common/io.py", line 84, in decorated
      return f(*args, **kwds)
    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda/gateways/connection/download.py", line 152, in download
      raise CondaSSLError(
  conda.exceptions.CondaSSLError: Encountered an SSL error. Most likely a certificate verification issue.

  Exception: HTTPSConnectionPool(host='last.cbrc.jp', port=443): Max retries exceeded with url: /last-874.zip (Caused by SSLError(SSLCertVerificationError("hostname 'last.cbrc.jp' doesn't match 'cbrc3.cbrc.jp'")))
# Last 100 lines of the build log.
