recipe_sha: 3e6544a08c4a9fffbd4f96990ee6921dd8de2b0b0a7d35f53e8785dce2482c3b  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
    912 |                         remaining_blocks = current_section->nb_blocks;
        |                                                             ^~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp: In member function 'void Kff_reader::read_next_block()':
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:920:9: error: 'current_seq_kmers' was not declared in this scope
    920 |         current_seq_kmers = remaining_kmers = current_section->read_compacted_sequence(current_sequence, current_data);
        |         ^~~~~~~~~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:920:29: error: 'remaining_kmers' was not declared in this scope
    920 |         current_seq_kmers = remaining_kmers = current_section->read_compacted_sequence(current_sequence, current_data);
        |                             ^~~~~~~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:920:64: error: 'class Block_section_reader' has no member named 'read_compacted_sequence'
    920 |         current_seq_kmers = remaining_kmers = current_section->read_compacted_sequence(current_sequence, current_data);
        |                                                                ^~~~~~~~~~~~~~~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:920:88: error: 'current_sequence' was not declared in this scope
    920 |         current_seq_kmers = remaining_kmers = current_section->read_compacted_sequence(current_sequence, current_data);
        |                                                                                        ^~~~~~~~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:920:106: error: 'current_data' was not declared in this scope
    920 |         current_seq_kmers = remaining_kmers = current_section->read_compacted_sequence(current_sequence, current_data);
        |                                                                                                          ^~~~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:921:9: error: 'current_seq_nucleotides' was not declared in this scope
    921 |         current_seq_nucleotides = remaining_kmers  current_section->k - 1;
        |         ^~~~~~~~~~~~~~~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:921:70: error: 'class Block_section_reader' has no member named 'k'
    921 |         current_seq_nucleotides = remaining_kmers  current_section->k - 1;
        |                                                                      ^
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:922:9: error: 'current_seq_bytes' was not declared in this scope
    922 |         current_seq_bytes = bytes_from_bit_array(2, current_seq_nucleotides);
        |         ^~~~~~~~~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:922:29: error: 'bytes_from_bit_array' was not declared in this scope
    922 |         current_seq_bytes = bytes_from_bit_array(2, current_seq_nucleotides);
        |                             ^~~~~~~~~~~~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:925:14: error: 'uint8_t' was not declared in this scope
    925 |         for (uint8_t i=1 ; i<4 ; i) {
        |              ^~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:925:14: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:925:28: error: 'i' was not declared in this scope
    925 |         for (uint8_t i=1 ; i<4 ; i) {
        |                            ^
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:927:24: error: 'current_shifts' was not declared in this scope
    927 |                 memcpy(current_shifts[i], current_sequence, current_seq_bytes);
        |                        ^~~~~~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:929:17: error: 'rightshift8' was not declared in this scope
    929 |                 rightshift8(current_shifts[i], current_seq_bytes, 2 * i);
        |                 ^~~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp: At global scope:
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:939:1: error: 'uint64_t' does not name a type
    939 | uint64_t Kff_reader::next_block(uint8_t* & sequence, uint8_t* & data) {
        | ^~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:939:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:963:6: error: variable or field 'next_kmer' declared void
    963 | void Kff_reader::next_kmer(uint8_t* & kmer, uint8_t* & data) {
        |      ^~~~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:963:28: error: 'uint8_t' was not declared in this scope
    963 | void Kff_reader::next_kmer(uint8_t* & kmer, uint8_t* & data) {
        |                            ^~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:963:28: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:963:39: error: 'kmer' was not declared in this scope
    963 | void Kff_reader::next_kmer(uint8_t* & kmer, uint8_t* & data) {
        |                                       ^~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:963:45: error: 'uint8_t' was not declared in this scope
    963 | void Kff_reader::next_kmer(uint8_t* & kmer, uint8_t* & data) {
        |                                             ^~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:963:45: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:963:56: error: 'data' was not declared in this scope
    963 | void Kff_reader::next_kmer(uint8_t* & kmer, uint8_t* & data) {
        |                                                        ^~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:1001:1: error: 'uint64_t' does not name a type
   1001 | uint64_t Kff_reader::get_var(string name) {
        | ^~~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:1001:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:1012:1: error: 'uint8_t' does not name a type
   1012 | uint8_t * Kff_reader::get_encoding() {
        | ^~~~~~~
  /opt/conda/conda-bld/minia_1734293897416/work/thirdparty/gatb-core/gatb-core/thirdparty/kff-cpp-api/kff_io.cpp:1012:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  make[2]: *** [ext/gatb-core/src/CMakeFiles/gatbcore-static.dir/build.make:1507: ext/gatb-core/src/CMakeFiles/gatbcore-static.dir/__/thirdparty/kff-cpp-api/kff_io.cpp.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  make[1]: *** [CMakeFiles/Makefile2:385: ext/gatb-core/src/CMakeFiles/gatbcore-static.dir/all] Error 2
  make: *** [Makefile:156: all] Error 2
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2558, in build
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/minia_1734293897416/work/conda_build.sh']' returned non-zero exit status 2.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
      raise BuildScriptException(str(exc), caused_by=exc) from exc
  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/minia_1734293897416/work/conda_build.sh']' returned non-zero exit status 2.
# Last 100 lines of the build log.
category: |-
  compiler error
