recipe_sha: 3670c5cd66f2af2eac4974abb2cc023792ab7d642e1b945c2b0d0482b7923f2f  # The commit at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  [?25hBUILD START: ['dialign-tx-1.0.2-h031d066_6.tar.bz2']
  [34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
  [?25l[2K[0G[] 0.0s
  [2K[1A[2K[0Gopt/conda/conda-bld/linux-64                       129.0 B @   2.1MB/s  0.0s
  opt/conda/conda-bld/noarch                         127.0 B @ 682.8kB/s  0.0s
  [?25h
  ## Package Plan ##

    environment location: /opt/conda/conda-bld/dialign-tx_1685391728126/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


  The following NEW packages will be INSTALLED:

      _libgcc_mutex: 0.1-conda_forge    conda-forge
      _openmp_mutex: 4.5-2_gnu          conda-forge
      libgcc-ng:     12.2.0-h65d4601_19 conda-forge
      libgomp:       12.2.0-h65d4601_19 conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  [34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
  [?25l[2K[0G[] 0.0s
  opt/conda/conda-bl..    [2K[1A[2K[0Gopt/conda/conda-bld/linux-64
  opt/conda/conda-bld/noarch                         127.0 B @   4.9MB/s  0.0s
  [?25h[34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
  [?25l[2K[0G[] 0.0s
  [2K[1A[2K[0Gopt/conda/conda-bld/linux-64                       129.0 B @   1.3MB/s  0.0s
  opt/conda/conda-bld/noarch                         127.0 B @   3.8MB/s  0.0s
  [?25h
  ## Package Plan ##

    environment location: /opt/conda/conda-bld/dialign-tx_1685391728126/_build_env


  The following NEW packages will be INSTALLED:

      _libgcc_mutex:           0.1-conda_forge    conda-forge
      _openmp_mutex:           4.5-2_gnu          conda-forge
      binutils_impl_linux-64:  2.39-he00db2b_1    conda-forge
      binutils_linux-64:       2.39-h5fc0e48_13   conda-forge
      gcc_impl_linux-64:       12.2.0-hcc96c02_19 conda-forge
      gcc_linux-64:            12.2.0-h4798a0e_13 conda-forge
      kernel-headers_linux-64: 2.6.32-he073ed8_15 conda-forge
      ld_impl_linux-64:        2.39-hcc3a1bd_1    conda-forge
      libgcc-devel_linux-64:   12.2.0-h3b97bd3_19 conda-forge
      libgcc-ng:               12.2.0-h65d4601_19 conda-forge
      libgomp:                 12.2.0-h65d4601_19 conda-forge
      libsanitizer:            12.2.0-h46fd767_19 conda-forge
      libstdcxx-ng:            12.2.0-h46fd767_19 conda-forge
      make:                    4.3-hd18ef5c_1     conda-forge
      sysroot_linux-64:        2.12-he073ed8_15   conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  Source cache directory is: /opt/conda/conda-bld/src_cache
  INFO:conda_build.source:Source cache directory is: /opt/conda/conda-bld/src_cache
  Downloading source to cache: DIALIGN-TX_1.0.2_fb3940a48a.tar.gz
  INFO:conda_build.source:Downloading source to cache: DIALIGN-TX_1.0.2_fb3940a48a.tar.gz
  Downloading http://dialign-tx.gobics.de/DIALIGN-TX_1.0.2.tar.gz
  INFO:conda_build.source:Downloading http://dialign-tx.gobics.de/DIALIGN-TX_1.0.2.tar.gz
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/DIALIGN-TX_1.0.2.tar.gz'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='dialign-tx.gobics.de', port=80): Read timed out. (read timeout=60.0)")': /DIALIGN-TX_1.0.2.tar.gz
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/DIALIGN-TX_1.0.2.tar.gz'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='dialign-tx.gobics.de', port=80): Read timed out. (read timeout=60.0)")': /DIALIGN-TX_1.0.2.tar.gz
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/DIALIGN-TX_1.0.2.tar.gz'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='dialign-tx.gobics.de', port=80): Read timed out. (read timeout=60.0)")': /DIALIGN-TX_1.0.2.tar.gz
  Error: HTTP 000 CONNECTION FAILED for url <http://dialign-tx.gobics.de/DIALIGN-TX_1.0.2.tar.gz>
  Elapsed: -

  An HTTP error occurred when trying to retrieve this URL.
  HTTP errors are often intermittent, and a simple retry will get you on your way.
  WARNING:conda_build.source:Error: HTTP 000 CONNECTION FAILED for url <http://dialign-tx.gobics.de/DIALIGN-TX_1.0.2.tar.gz>
  Elapsed: -

  An HTTP error occurred when trying to retrieve this URL.
  HTTP errors are often intermittent, and a simple retry will get you on your way.
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
      call_conda_build(action, config)
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
      result = api.build(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
      return build_tree(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
      packages_from_this = build(metadata, stats,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2125, in build
      try_download(m, no_download_source=False, raise_error=True)
    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 650, in try_download
      source.provide(metadata)
    File "/opt/conda/lib/python3.8/site-packages/conda_build/source.py", line 871, in provide
      unpack(source_dict, src_dir, metadata.config.src_cache, recipe_path=metadata.path,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/source.py", line 146, in unpack
      src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)
    File "/opt/conda/lib/python3.8/site-packages/conda_build/source.py", line 102, in download_to_cache
      raise RuntimeError("Could not download %s" % url)
  RuntimeError: Could not download http://dialign-tx.gobics.de/DIALIGN-TX_1.0.2.tar.gz
# Last 100 lines of the build log.
