recipe_sha: bae31bf67e7e036baac5d5fd4dbf402b9175e4f083083a9fd4640235a68454f8  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    exit status: 0
    cargo:rerun-if-env-changed=AR_x86_64-unknown-linux-gnu
    AR_x86_64-unknown-linux-gnu = None
    cargo:rerun-if-env-changed=AR_x86_64_unknown_linux_gnu
    AR_x86_64_unknown_linux_gnu = None
    cargo:rerun-if-env-changed=HOST_AR
    HOST_AR = None
    cargo:rerun-if-env-changed=AR
    AR = Some(/opt/conda/conda-bld/flopp_1733852626676/_build_env/bin/x86_64-conda-linux-gnu-ar)
    cargo:rerun-if-env-changed=ARFLAGS_x86_64-unknown-linux-gnu
    ARFLAGS_x86_64-unknown-linux-gnu = None
    cargo:rerun-if-env-changed=ARFLAGS_x86_64_unknown_linux_gnu
    ARFLAGS_x86_64_unknown_linux_gnu = None
    cargo:rerun-if-env-changed=HOST_ARFLAGS
    HOST_ARFLAGS = None
    cargo:rerun-if-env-changed=ARFLAGS
    ARFLAGS = None
    cargo:rustc-link-lib=static=hts
    cargo:rustc-link-search=native=/opt/conda/conda-bld/flopp_1733852626676/work/target/release/build/hts-sys-20b0b0fae09bea42/out

    --- stderr
    thread 'main' panicked at /opt/conda/conda-bld/flopp_1733852626676/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.69.5/lib.rs:622:31:
    Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (invalid: [])"
    stack backtrace:
       0: rust_begin_unwind
       1: core::panicking::panic_fmt
       2: core::result::unwrap_failed
       3: core::result::Result<T,E>::expect
       4: core::ops::function::FnOnce::call_once
       5: lazy_static::lazy::Lazy<T>::get::{{closure}}
       6: std::sync::once::Once::call_once::{{closure}}
       7: std::sys::sync::once::futex::Once::call
       8: std::sync::once::Once::call_once
       9: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
      10: bindgen::ensure_libclang_is_loaded
      11: bindgen::Bindings::generate
      12: bindgen::Builder::generate
      13: build_script_build::main
      14: core::ops::function::FnOnce::call_once
    note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
  error: failed to compile flopp v0.2.0 (/opt/conda/conda-bld/flopp_1733852626676/work), intermediate artifacts can be found at /opt/conda/conda-bld/flopp_1733852626676/work/target.
  To reuse those artifacts with a future compilation, set the environment variable CARGO_TARGET_DIR to that path.
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2558, in build
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/flopp_1733852626676/work/conda_build.sh']' returned non-zero exit status 101.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
      raise BuildScriptException(str(exc), caused_by=exc) from exc
  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/flopp_1733852626676/work/conda_build.sh']' returned non-zero exit status 101.
# Last 100 lines of the build log.
