recipe_sha: 22a901ca8432967438dc958f38db77d69f7fe5b8640b1ed214d8cc97380db6e1  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
     INFO (sequenza-utils,lib/python3.12/site-packages/sequenza/c_pileup.cpython-312-darwin.so): Needed DSO /System/Library/Frameworks/libSystem.B.dylib found in $SYSROOT
  WARNING (sequenza-utils): dso library package conda-forge/osx-64::libcxx==19.1.5=hf95d169_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to build/ignore_run_exports)
  WARNING (sequenza-utils): interpreter (Python) package conda-forge/osx-64::python==3.12.8=h9ccd52b_1_cpython in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to build/ignore_run_exports)
  Fixing permissions
  INFO :: Time taken to mark (prefix)
          0 replacements in 0 files was 0.12 seconds
  Files containing CONDA_PREFIX
  -----------------------------
  bin/sequenza-utils (text): Patching
  TEST START: /opt/mambaforge/envs/bioconda/conda-bld/osx-64/sequenza-utils-3.0.0-py312h692437a_8.tar.bz2
  Renaming work directory '/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/work' to '/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/work_moved_sequenza-utils-3.0.0-py312h692437a_8_osx-64'
  shutil.move(work)=/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/work, dest=/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/work_moved_sequenza-utils-3.0.0-py312h692437a_8_osx-64)
  Reloading output folder (local): ...working... done
  Solving environment (_test_env): ...working... done

  ## Package Plan ##

    environment location: /opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac


  The following NEW packages will be INSTALLED:

      bzip2:           1.0.8-hfdf4475_7          conda-forge
      c-ares:          1.34.4-hf13058a_0         conda-forge
      ca-certificates: 2024.12.14-h8857fd0_0     conda-forge
      htslib:          1.21-h9f635df_1           bioconda
      krb5:            1.21.3-h37d8d59_0         conda-forge
      libcurl:         8.11.1-h5dec5d8_0         conda-forge
      libcxx:          19.1.5-hf95d169_0         conda-forge
      libdeflate:      1.22-h00291cd_0           conda-forge
      libedit:         3.1.20191231-h0678c8f_2   conda-forge
      libev:           4.33-h10d778d_2           conda-forge
      libexpat:        2.6.4-h240833e_0          conda-forge
      libffi:          3.4.2-h0d85af4_5          conda-forge
      liblzma:         5.6.3-hd471939_1          conda-forge
      libnghttp2:      1.64.0-hc7306c3_0         conda-forge
      libsqlite:       3.47.2-hdb6dae5_0         conda-forge
      libssh2:         1.11.1-h3dc7d44_0         conda-forge
      libzlib:         1.3.1-hd23fc13_2          conda-forge
      ncurses:         6.5-hf036a51_1            conda-forge
      openssl:         3.4.0-hd471939_0          conda-forge
      python:          3.12.8-h9ccd52b_1_cpython conda-forge
      python_abi:      3.12-5_cp312              conda-forge
      readline:        8.2-h9e318b2_1            conda-forge
      samtools:        1.21-ha21ef43_1           bioconda
      sequenza-utils:  3.0.0-py312h692437a_8     local
      tk:              8.6.13-h1abcd95_1         conda-forge
      tzdata:          2024b-hc8b5060_0          conda-forge
      zstd:            1.5.6-h915ae27_0          conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
   sequenza-utils --help
  Traceback (most recent call last):
    File "/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/sequenza-utils", line 11, in <module>
      sys.exit(main())
               ^^^^^^
    File "/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/sequenza/commands.py", line 30, in main
      modules = get_modules(sequenza.programs, subparsers, {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/sequenza/misc.py", line 73, in get_modules
      __import__(mod)
    File "/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/sequenza/programs/bam2seqz.py", line 5, in <module>
      from sequenza.samtools import bam_mpileup, indexed_pileup, tabix_seqz
    File "/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/sequenza/samtools.py", line 6, in <module>
      from distutils.spawn import find_executable
  ModuleNotFoundError: No module named 'distutils'
  WARNING: Tests failed for sequenza-utils-3.0.0-py312h692437a_8.tar.bz2 - moving package to /opt/mambaforge/envs/bioconda/conda-bld/broken
  Traceback (most recent call last):
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3523, in test
  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/test_tmp
  import: 'sequenza'
  import: 'sequenza.programs'
  import: 'sequenza'
  import: 'sequenza.programs'
      utils.check_call_env(
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/sequenza-utils_1734380101504/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3727, in build_tree
      test(pkg, config=metadata.config.copy(), stats=stats)
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3537, in test
      tests_failed(
    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3584, in tests_failed
      raise CondaBuildUserError("TESTS FAILED: "  os.path.basename(pkg))
  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: sequenza-utils-3.0.0-py312h692437a_8.tar.bz2
# Last 100 lines of the build log.
